name: tugaskuapp
description: "Aplikasi Tugasku"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-322.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  dropdown_search: ^6.0.1
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  file_picker: ^6.1.1
  cloudinary: ^1.2.0
  uuid: ^4.5.1
  path: ^1.9.0
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5
  dio: ^5.7.0
  open_file: ^3.5.10
  workmanager: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/IconApp.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/IconApp.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/IconApp.png"
    icon_size: 48


flutter:
  uses-material-design: true
  assets:
    - assets/
